server:
  port: 9999
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://101.37.158.1:3306/im_project?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
#  redis:
#    database: 0
#    host: 101.37.158.1
#    port: 6379
#    timeout: 1000
#    poolMaxTotal: 1000
#    poolMaxIdle: 500
#    poolMaxWait: 500
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.tdk.entity  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true